spring.datasource.url=jdbc:postgresql://localhost:5432/reviewforge
spring.datasource.username=postgres
spring.datasource.password=Akhsuna03

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.tool.schema=DEBUG